//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2022 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::_root_attributes.asciidoc[]

indexterm:[release, notes]

[[release-notes-chapter-index]]
== Chi release notes

The release notes for the versions of Chi and the associated tools, as part of the Eclipse ESCET project, are listed below in reverse chronological order.

The release notes may refer to issues, the details for which can be found at the Eclipse ESCET link:https://gitlab.eclipse.org/eclipse/escet/escet/-/issues[GitLab issues page].

See also the Eclipse ESCET link:https://eclipse.org/escet/{escet-website-version}/release-notes.html[toolkit release notes] covering those aspects that are common to the various Eclipse ESCET tools.

=== Version 0.6

TBD

Improvements and fixes:

* Improved bibliography references in documentation (issue #365).
* Small website style improvements (issue #367).

=== Version 0.5 (2022-03-29)

Improvements and fixes:

* Some small changes to the documentation (issue #271).
* The release notes for each version now contain the release date, with the exception of milestone releases and release candidates (issue #314).

=== Version 0.4 (2021-12-17)

Improvements and fixes:

* Introduced a brand new website (issue #35).
* Many website URLs have changed due to various website structure changes (issues #35 and #73).
* Various documentation/website textual improvements, style improvements and other changes (issues #35, #54, #236 and #248).
* The Chi simulator SVG visualizer functionality to save the image as an SVG file no longer crashes (issue #205).
* The Chi simulator SVG visualizer functionality to save as an image no longer asks duplicate overwrite questions (issue #223).
* The Chi simulator no longer crashes when showing an SVG visualizer if the SVG file can't be loaded (issue #207).

=== Version 0.3 (2021-10-01)

Improvements and fixes:

* The website and Eclipse help now use multi-page HTML rather than a single HTML file, although the website still contains a link to the single-page HTML that allows easily searching the full documentation (issue #36).
* Enabled section anchors for documentation on the website, and disabled section anchors for Eclipse help (issue #36).
* Several small documentation fixes and improvements (issues #36 and #166).

=== Version 0.2 (2021-07-07)

Improvements and fixes:

* Chi simulator no longer crashes when using the Eclipse Compiler for Java (ecj) as Java compiler (issue #46).

=== Version 0.1 (2021-04-02)

The first release of Chi as part of the Eclipse ESCET project.
This release is based on the initial contribution by the Eindhoven University of Technology (TU/e).

Most notable changes compared to the last TU/e release:

* The Chi simulator no longer crashes on code generation.
