//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::_root_attributes.asciidoc[]

indexterm:[release, notes]

[[release-notes-chapter-index]]
== Chi release notes

The release notes for the versions of Chi and the associated tools, as part of the Eclipse ESCET project, are listed below in reverse chronological order.

See also the Eclipse ESCET link:https://eclipse.org/escet/{escet-website-version}/release-notes.html[toolkit release notes] covering those aspects that are common to the various Eclipse ESCET tools.

=== Version 0.9

TBD

=== Version 0.8 (2022-12-21)

Improvements and fixes:

* Normally, `.chi` files are opened with the Chi text editor.
Large files are now however opened with the default non-Chi text editor to avoid performance issues.
You can open a file in an editor of your choosing by right clicking it and selecting menu:Open With[] and then selecting the editor of your choosing, or choosing menu:Other...[] to open a dialog to choose from a larger selection of editors (issue {escet-issue}199[#199]).

=== Version 0.7 (2022-09-30)

New features:

* The Chi text editor now has theming support, and comes with a dark theme in addition to the existing light theme.
The text editor now automatically uses its dark theme when the Eclipse built-in dark theme is used, and uses a light theme otherwise.
The text editor theming behavior can be configured via the Eclipse Preferences dialog (issue {escet-issue}347[#347]).

Improvements and fixes:

* The Chi text editor light theme's default color has changed from a near-black slightly-brown color to pure black (issue {escet-issue}347[#347]).

=== Version 0.6 (2022-07-07)

Improvements and fixes:

* Links in the documentation to non-Chi ESCET documentation webpages now use version-specific URLs (issue {escet-issue}386[#386]).
* Improved bibliography references in documentation (issue {escet-issue}365[#365]).
* The issue numbers in the release notes now link to the corresponding GitLab issue (issue {escet-issue}396[#396]).
* Small website style improvements (issue {escet-issue}367[#367]).

=== Version 0.5 (2022-03-29)

Improvements and fixes:

* Some small changes to the documentation (issue {escet-issue}271[#271]).
* The release notes for each version now contain the release date, with the exception of milestone releases and release candidates (issue {escet-issue}314[#314]).

=== Version 0.4 (2021-12-17)

Improvements and fixes:

* Introduced a brand new website (issue {escet-issue}35[#35]).
* Many website URLs have changed due to various website structure changes (issues {escet-issue}35[#35] and {escet-issue}73[#73]).
* Various documentation/website textual improvements, style improvements and other changes (issues {escet-issue}35[#35], {escet-issue}54[#54], {escet-issue}236[#236] and {escet-issue}248[#248]).
* The Chi simulator SVG visualizer functionality to save the image as an SVG file no longer crashes (issue {escet-issue}205[#205]).
* The Chi simulator SVG visualizer functionality to save as an image no longer asks duplicate overwrite questions (issue {escet-issue}223[#223]).
* The Chi simulator no longer crashes when showing an SVG visualizer if the SVG file can't be loaded (issue {escet-issue}207[#207]).

=== Version 0.3 (2021-10-01)

Improvements and fixes:

* The website and Eclipse help now use multi-page HTML rather than a single HTML file, although the website still contains a link to the single-page HTML that allows easily searching the full documentation (issue {escet-issue}36[#36]).
* Enabled section anchors for documentation on the website, and disabled section anchors for Eclipse help (issue {escet-issue}36[#36]).
* Several small documentation fixes and improvements (issues {escet-issue}36[#36] and {escet-issue}166[#166]).

=== Version 0.2 (2021-07-07)

Improvements and fixes:

* Chi simulator no longer crashes when using the Eclipse Compiler for Java (ecj) as Java compiler (issue {escet-issue}46[#46]).

=== Version 0.1 (2021-04-02)

The first release of Chi as part of the Eclipse ESCET project.
This release is based on the initial contribution by the Eindhoven University of Technology (TU/e).

Most notable changes compared to the last TU/e release:

* The Chi simulator no longer crashes on code generation.
