//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2021 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::../../../_part_attributes.asciidoc[]

[[tools-cifsim-output-svgviz-chapter-viewer]]
== SVG viewer and visualizer

indexterm:[SVG,viewer]
indexterm:[SVG viewer]
indexterm:[SVG visualization,visualizer]
indexterm:[see: SVG visualizer,SVG visualization]
indexterm:[see: SVG visualizer,SVG viewer]
Our software comes with an SVG viewer for Eclipse.
SVG image files can now be opened for viewing within Eclipse.
This same viewer is used as a basis for the SVG visualizer used by the CIF simulator.

=== SVG viewer

Opening SVG files in Eclipse results in them being opened by the SVG viewer.
The SVG viewer can be used to preview SVG images from within Eclipse.

If the SVG viewer can not open an SVG image, for instance because it contains <<tools-cifsim-output-svgviz-svg-svg11,unsupported features>> such as <<tools-cifsim-output-svgviz-inkscape-textarea,text areas>>, the SVG viewer will indicate this.
Therefore, opening an SVG image in Eclipse can be used to verify that the SVG image can be used for SVG visualization.

indexterm:[SVG viewer,refresh]

=== Refresh

The SVG viewer does _not_ refresh its display if the image file is changed.
To refresh the image, close the image, and open it again.

indexterm:[SVG viewer,save as]
indexterm:[SVG viewer,export]
indexterm:[SVG viewer,PNG]
indexterm:[SVG viewer,JPEG]
indexterm:[SVG viewer,GIF]
indexterm:[SVG viewer,SVG]

[[tools-cifsim-output-svgviz-viewer-saveas]]
=== Save as

The SVG viewer and SVG visualizer can export the currently visible image to several different image formats.
To export the image, first make sure that the SVG viewer or SVG visualizer has the focus.
Then select menu:File[Save As...] to open the _Save SVG as_ dialog.
Alternatively, right click the SVG image itself, and choose menu:Save As...[] from the popup menu, to open the _Save SVG as_ dialog.
In the dialog, specify the file name of the exported image.
Click btn:[OK] to confirm and to actually export the image.

The following link:http://en.wikipedia.org/wiki/Raster_graphics[raster image] formats are supported:

* link:http://en.wikipedia.org/wiki/Portable_Network_Graphics[Portable Network Graphics] (`+*.png+`)

* link:http://en.wikipedia.org/wiki/JPEG[JPEG] (`+*.jpg+`)

* link:http://en.wikipedia.org/wiki/Graphics_Interchange_Format[Graphics Interchange Format] (`+*.gif+`)

The following link:http://en.wikipedia.org/wiki/Vector_graphics[vector image] formats are supported:

* link:http://en.wikipedia.org/wiki/Scalable_Vector_Graphics[Scalable Vector Graphics] (`*.svg`)

The image format that is used to export the image, is derived from the file extension that is used.
For each of the supported file formats, the allowed file names (with file extensions) are indicated above (between parentheses).

After the image is exported, the workspace is refreshed to show that new image file, if the image was saved in a project that is visible in the _Project Explorer_ tab or _Package Explorer_ tab.
