<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TcPlcObject ProductVersion="3.1.0.18" Version="1.1.0.1">
  <POU Name="alg_g_a_x">
    <Declaration>
      <![CDATA[FUNCTION alg_g_a_x: LREAL
VAR_INPUT
    state: STATE;
END_VAR]]>
    </Declaration>
    <Implementation>
      <ST>
        <![CDATA[alg_g_a_x := state.curTime;]]>
      </ST>
    </Implementation>
    <ObjectProperties/>
  </POU>
</TcPlcObject>
