//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::../_part_attributes.asciidoc[]

[[lang-tut-values-chapter-if-and-switch]]
== If and switch expressions

indexterm:[if]
indexterm:[expression,if]
indexterm:[if,expression]

[[lang-tut-values-chapter-if-expression]]
=== If expression

It is possible to perform different calculations under different circumstances.
Consider the following expression:

[source, cif]
----
if x > 0: 1 elif x < 0: -1 else 0 end
----

This expression takes a real number `x` and calculates its link:https://en.wikipedia.org/wiki/Signum_function[sign].
The `if` expression is used to detect the different situations, and to return the correct result in each of those situations.

An `if` expression always consist of the `if` and the `else` part.
But the number of `elif` parts is free, and it could be omitted altogether:

[source, cif]
----
if x > 0: 1 elif x < 0: -1 else 0 end
if x > 0: 1 else 0 end
if x > 0: 1 elif x < -10: -2 elif x < 0: -1 else 0 end
----

The 'guard predicate' of an `if` or `elif` (the expression before the `:`) can be any expression that evaluates to a boolean value.
The type of the ‘then’ expression, the type of the ‘else’ expression, the types of the ‘thens’ of the `elif` expressions (if any) must all match:

[source, cif]
----
if x > 0 and y == 2: 1.5 elif x > 0 and y != 2 or x < 0: -2.8 else 0.1 end
----

The `if` and `elif` guard predicates are processed in order. So once one is evaluated to true, the 'then' of that expression is evaluated and the remainder of the `elif` expressions and the `else` are skipped.
Consider the following `if` expression.

[source, cif]
----
if x > 0: 1.5 elif x > 0: -2.8 else 0.1 end
----

For any value `x > 0`, this `if` expression returns `1.5`.
It will never return `-2.8`, as the `if` part is evaluated before the `elif` part.

indexterm:[switch]
indexterm:[expression,switch]
indexterm:[switch,expression]

[[lang-tut-values-chapter-switch-expression]]
=== Switch expression

Similar to the `if` expressions, a `switch` expression can be used to perform different calculations under different circumstances.
Consider the following partial CIF model:

[source, cif]
----
enum mode = OFF, ON1, ON2, ON3, DISCONNECTED;
automaton rotary_switch:
  disc mode m = OFF;
  ...
end

alg int speed = switch rotary_switch.m:
  case ON1: 5
  case ON2: 10
  case ON3: 15
  else      0
  end;
end
----

This `switch` expression takes the operation mode `rotary_switch.m` and provides the speed corresponding to that mode.
If the value of `rotary_switch.m` matches one of the cases, the `switch` expression will evaluate to the corresponding value.
For example, if `rotary_switch.m = ON2`, this `switch` expression evaluates to `10`.
If none of the cases matches, the value of the `else` case is taken.
For example, if `rotary_switch.m = DISCONNECTED`, this `switch` expression evaluates to `0`.
Note that multiple values can be captured by the `else` case, i.e., you do not have to cover each possible value with a separate case.

One can use all elementary and container types from <<lang-tut-values-chapter-overview>>, including user-defined types, as long as the types of the cases matches the type of the switch expression.
In the example, `rotary_switch.m` is of type `mode`, which is an enumeration.
Hence all cases should be of type `mode` as well.

One can also use an automaton as a type of the `switch` expression, where the cases have to be locations of that automaton:

[source, cif]
----
automaton controller:
  location accelerate: ...
  location decelerate: ...
  location steady: ...
end

alg int acceleration = switch controller:
  case accelerate:  5
  case decelerate: -3
  case steady:      0
  end;
----

Observe that in this `switch` expression we omitted the `else` case.
The `else` case is allowed to be omitted if all the cases together cover all possible values of the `switch` expression.
In the example above, the three cases cover all possible locations of automaton `controller`.

`if` expressions and `switch` expressions are very similar.
It is possible to rewrite a `switch` expression into an `if` expression.
See <<tools-cif2cif-chapter-switches-to-ifs>> for the CIF to CIF transformation tool to do this automatically.
