<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TcPlcObject ProductVersion="3.1.0.18" Version="1.1.0.1">
  <POU Name="alg_a">
    <Declaration><![CDATA[FUNCTION alg_a: LREAL
VAR_INPUT
    state: STATE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a := (state.cvar_c) + (derivcvar_c(state));]]></ST>
    </Implementation>
    <ObjectProperties/>
  </POU>
</TcPlcObject>
