/////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2020 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the terms
// of the MIT License which is available at https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
/////////////////////////////////////////////////////////////////////////////////

include::_part_attributes.asciidoc[]

[[intro-chapter-index]]
== Introduction to Eclipse ESCET project

indexterm:[project, ESCET]

High-tech companies increasingly adopt the
link:https://en.wikipedia.org/wiki/Model-based_systems_engineering[Model-Based Systems Engineering]
(MBSE) paradigm. The use of (formal) models for controller design allows
validation and verification of controllers long before they are implemented
and integrated into the system. Early validation and verification have been
shown to lead to less defects and reduced costs.

indexterm:[MBSE]

The Eclipse Supervisory Control Engineering Toolkit (Eclipse ESCET) project is
an link:https://eclipse.org[Eclipse] project that provides a toolkit for the
development of supervisory controllers in the MBSE paradigm. The toolkit has
a strong focus on model-based design, supervisory controller synthesis, and
industrial applicability, for example to cyber physical systems. The toolkit
supports the entire development process of (supervisory) controllers, from
modeling, supervisory controller synthesis, simulation-based validation and
visualization, and formal verification, to real-time testing and
implementation.

indexterm:[synthesis]

Supervisory controller synthesis is a key feature of the toolkit. It
involves the automatic generation of supervisory controllers from a
specification of the uncontrolled system and the (safety) requirements that
the controller needs to enforce. This shifts controller design from 'how
should the implementation work' to 'what should the controller do'.
Implementation of the controller is achieved through (implementation
language) code generation, reducing the number of errors introduced at this
stage.

The Eclipse ESCET toolkit features the following languages and associated
tools:

* <<intro-chapter-chi,Chi>>
* <<intro-chapter-cif,CIF>>
* <<intro-chapter-setext,SeText>>
* <<intro-chapter-tooldef,ToolDef>>
