/////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2021 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the terms
// of the MIT License which is available at https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
/////////////////////////////////////////////////////////////////////////////////

include::_part_attributes.asciidoc[]

indexterm:[ToolDef]

[[intro-chapter-tooldef]]
== ToolDef

ToolDef is a cross-platform and machine-independent scripting language.
It supports command line execution, but is also available as plug-in for
the Eclipse IDE, providing an integrated development experience.

The ToolDef language features a simple and intuitive syntax to make it easy to
write scripts, static typing to catch simple mistakes, a large number of
built-in data types and tools, Java integration, and more.

ToolDef libraries with ToolDef compatible tools are available for all tools
within the Eclipse ESCET toolkit, allowing cross-platform and
machine-independent scripting using Eclipse ESCET tools. ToolDef however is a
generic scripting language, and can be used without using any of the other
Eclipse ESCET tools. Furthermore, other tools can be made available for use
within ToolDef scripts by defining ToolDef libraries for them.

See the separate ToolDef documentation for more information.
