//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::../_part_attributes.asciidoc[]

[[lang-ref-syntax-xmi]]
== CIF XMI files

While CIF has a textual syntax (see the <<lang-ref-syntax-lexical,lexical syntax>> and <<lang-ref-syntax-grammar,grammar>>), in certain cases it may be more convenient to work with CIF specifications as XML files.
For instance:

* When debugging tools that produce CIF models, the XML file format contains all internal details, such as the types of expressions.
* For processing of CIF specifications by other tools, having an XML syntax can be useful as well.
Those tools do not have to parse and type check CIF specifications by themselves, as the XML files contain the type checked specifications.

All CIF tools bundled with Eclipse ESCET support writing CIF specifications as link:https://en.wikipedia.org/wiki/XML_Metadata_Interchange[XMI] files, XML files with unique identifiers for all objects.
To write a CIF XMI file instead of a regular CIF file in the CIF textual syntax, use the `.cifx` file extension for the output CIF file.

All CIF tools bundled with Eclipse ESCET also support reading CIF specifications from XMI files.
If an input CIF specification has the `.cifx` file extension, it is read as an XMI file.

XMI files produced by different versions of CIF may not be compatible.
No care is taken to prevent such incompatibilities.
And the CIF <<release-notes-chapter-index,release notes>> do not indicate such incompatibilities.
