/////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2021 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the terms
// of the MIT License which is available at https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
/////////////////////////////////////////////////////////////////////////////////

include::_part_attributes.asciidoc[]

indexterm:[Checkstyle]
indexterm:[formatting]

[[developer-coding-standards-chapter-index]]
== Coding standards

The Eclipse ESCET <<developer-dev-env-setup-chapter-index,development environment>> has some features that allow developing high quality contributions:

* A Java formatter profile is included.
It allows to automatically format Java code for consistency and convenience.

* The link:https://checkstyle.org/eclipse-cs[Eclipse Checkstyle Plugin] and a Checkstyle configuration are included.
They can be used to detect various other issues in Java code and other files.

For all contributions to the Eclipse ESCET project, check the following:

* All Java code should be formatted using the provided formatting profile.

* All contributions should be checked using the provided Checkstyle configuration.

* All contributions should be free of warnings and errors, when working with them in the Eclipse ESCET development environment.

Remember that <<developer-contributing-chapter-index,contributions>> are always welcome, and contributions don't have to be perfect.
The project's developers can help to improve your contribution, and ensure it adheres to these coding standards.

For any questions regarding these coding standards, please <<developer-chapter-index,contact>> the project's developers.
