//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::_root_attributes.asciidoc[]

indexterm:[release, notes]

[[release-notes-chapter-index]]
== Eclipse ESCET release notes

The release notes for the versions of the Eclipse ESCET tools, as part of the Eclipse ESCET project, are listed below in reverse chronological order.

See also the release notes for the specific tools for more information:

* link:https://eclipse.dev/escet/{escet-deploy-folder-name}/cif/release-notes.html[CIF release notes]
* link:https://eclipse.dev/escet/{escet-deploy-folder-name}/chi/release-notes.html[Chi release notes]
* link:https://eclipse.dev/escet/{escet-deploy-folder-name}/tooldef/release-notes.html[ToolDef release notes]

=== Version 2.0

TBD

New features:

* The Eclipse ESCET project now deploys 'nightlies', in-development versions of the ESCET website and toolkit.
See the nightly website at https://eclipse.dev/escet/nightly/.
From the nightly website the nightly releases can be downloaded (issue {escet-issue}699[#699]).

Improvements and fixes:

* The Linux command line scripts for all ESCET tools no longer show a popup dialog upon exiting with a non-zero exit code (issue {escet-issue}89[#89]).
* The warning and error output on the Eclipse console for all ESCET tools now use different colors.
Warning output is now printed in yellow, error output still in red (issue {escet-issue}524[#524]).

=== Version 1.0 (2023-09-30)

Improvements and fixes:

* The Eclipse ESCET project has graduated.
The project has left the 'incubation' phase, and has entered the 'mature' phase.
In honor of this occasion, we leave the '0.x' version numbering behind.
All indications of the incubation phase have been removed.
This also leads to changes in download filenames (issues {escet-issue}614[#614] and {escet-issue}647[#647]).
* The DSM clustering tool's DSM input file format has been changed from a CSV-like file to an RFC-4180 compliant CSV file.
Tab characters are no longer supported in the input files (issue {escet-issue}629[#629]).

=== Version 0.10 (2023-06-30)

Improvements and fixes:

* The Eclipse ESCET website has moved from `www.eclipse.org/escet` to `eclipse.dev/escet`.
Redirects from the old URLs to the new ones are in place (issue {escet-issue}577[#577]).
* This release is based on Eclipse 2023-03, rather than Eclipse 2022-06 (issue {escet-issue}399[#399]).
* The Eclipse ESCET IDE no longer gives warnings for projects without an explicit encoding (issue {escet-issue}399[#399]).
* The DSM clustering tool's command line script for Linux is now executable (issue {escet-issue}570[#570]).
* The SVG viewer's _Save as_ dialog now properly starts in the directory that contains the SVG file, also on Windows.
And it now properly handles paths with spaces and other special characters in them (issue {escet-issue}221[#221]).

=== Version 0.9 (2023-03-31)

Improvements and fixes:

* The ESCET download page information for macOS has been updated to describe macOS Ventura (issue {escet-issue}483[#483]).
* Eclipse ESCET is now released for the both the x86_64 and aarch64 architectures of macOS (issue {escet-issue}484[#484]).
* Version-specific versions of the Eclipse ESCET website are no longer indexed by search engines.
Only the current version of the website is now indexed.
It may take some time for all search engines to catch up (issue {escet-issue}488[#488]).
* The DSM clustering tool now outputs files with proper and consistent line endings (issue {escet-issue}540[#540]).

=== Version 0.8 (2022-12-21)

Improvements and fixes:

* This release is based on Eclipse 2022-06, rather than Eclipse 2021-06 (issue {escet-issue}176[#176]).
* Eclipse 2022-06 may show for all projects in your existing workspace a warning that they don't have an explicit encoding set.
To get rid of the warning, open the _Problems_ view via menu:Window[Show View > Problems].
Then right click the warning and choose menu:Quick Fix[].
In the _Quick Fix_ dialog, click btn:[Select All] to select all projects, and then click btn:[Finish] to add the UTF-8 encoding to each project (issue {escet-issue}176[#176]).
* Eclipse 2022-06 may automatically use a dark theme if your operating system is configured to use a dark theme.
To explicitly choose either a light theme or a dark theme, open the _Preferences_ dialog via menu:Window[Preferences].
Then select menu:General[Appearance], and for _Theme_ select either _Light_ or _Dark_.
Select _System_ to automatically select light or dark mode based on the operating system settings (issue {escet-issue}176[#176]).
* The _Console_ view now has theming support, and comes with a dark theme in addition to the existing light theme.
The console now automatically uses its dark theme when the Eclipse built-in dark theme is used, and uses a light theme otherwise (issue {escet-issue}417[#417]).
* The _Application_ view's status legend has been redesigned to support both light and dark themes (issue {escet-issue}417[#417]).
* Improved the Eclipse ESCET IDE welcome screen, by making it fit better with the used theme, by adding some useful links to get started, and more (issue {escet-issue}32[#32]).
* Very long lines in the _Console_ view and text editors now render correctly on Windows (issue {escet-issue}76[#76]).
* Eclipse ESCET now bundles Java 17 rather than Java 11 (issue {escet-issue}259[#259]).
* The website of the current Eclipse ESCET release no longer links to version-specific URLs (issue {escet-issue}394[#394]).

=== Version 0.7 (2022-09-30)

This release contains no changes that apply to the Eclipse ESCET toolkit in general.
Consult the release notes for the specific tools for their changes.

=== Version 0.6 (2022-07-07)

New features:

* Added new Design Structure Matrix (DSM) clustering tool (issue {escet-issue}344[#344]).

Improvements and fixes:

* The Eclipse ESCET IDE is no longer configured with a maximum Java object heap size of 4 GB of memory.
The Java Virtual Machine (JVM) now decides the maximum, which may differ for different systems.
It is of course still possible to <<performance-tweak-perf-settings,configure the maximum yourself>> (issue {escet-issue}374[#374]).
* Links in the documentation to Chi, CIF and ToolDef documentation webpages now use version-specific URLs (issue {escet-issue}386[#386]).
* The issue numbers in the release notes now link to the corresponding GitLab issue (issue {escet-issue}396[#396]).
* Small website style improvements (issue {escet-issue}367[#367]).

=== Version 0.5 (2022-03-29)

Improvements and fixes:

* Some small changes to the documentation and website (issues {escet-issue}271[#271] and {escet-issue}335[#335]).
* The release notes for each version now contain the release date, with the exception of milestone releases and release candidates (issue {escet-issue}314[#314]).

=== Version 0.4 (2021-12-17)

Improvements and fixes:

* Introduced a brand new website (issue {escet-issue}35[#35]).
* Many website URLs have changed due to various website structure changes (issues {escet-issue}35[#35] and {escet-issue}73[#73]).
* Various documentation/website textual improvements, style improvements and other changes (issues {escet-issue}35[#35] and {escet-issue}54[#54]).
* The Eclipse ESCET end-user and development documentation have been split into two separate documentation sets (issue {escet-issue}73[#73]).
* SeText is now considered an internal developers tool.
It no longer has a website of its own.
Its documentation is now part of the Eclipse ESCET development documentation (issue {escet-issue}73[#73]).
* The Eclipse ESCET IDE executable is now named `eclipse-escet` or `eclipse-escet.exe`.
`eclipse.ini` is now named `eclipse-escet.ini` (issue {escet-issue}98[#98]).
* Eclipse ESCET now bundles Java 11.0.12 rather than Java 11.0.2 (issue {escet-issue}237[#237]).

=== Version 0.3 (2021-10-01)

Improvements and fixes:

* The website and Eclipse help now use multi-page HTML rather than a single HTML file, although the website still contains a link to the single-page HTML that allows easily searching the full documentation (issue {escet-issue}36[#36]).
* Enabled section anchors for documentation on the website, and disabled section anchors for Eclipse help (issue {escet-issue}36[#36]).
* Fixed macOS-specific instructions for tweaking Java performance settings via `eclipse.ini` (issue {escet-issue}179[#179]).
* Removed unsupported in-place update instructions from the documentation (issue {escet-issue}166[#166]).
* Several small documentation fixes and improvements (issue {escet-issue}166[#166]).

=== Version 0.2 (2021-07-07)

Improvements and fixes:

* Various documentation updates, including simpler installation instructions (issues {escet-issue}30[#30] and {escet-issue}31[#31]).
* Java 11 is now included in the release and Java thus no longer needs to be installed separately (issues {escet-issue}29[#29] and {escet-issue}30[#30]).
* The Eclipse ESCET IDE now includes the Eclipse Marketplace (issue {escet-issue}71[#71]).
* Linux command line scripts now work properly from any directory rather than only from the `bin` directory that contains them (issue {escet-issue}88[#88]).
* macOS releases are now packaged as `.dmg` files and with proper entitlements (issue {escet-issue}21[#21]).
* Eclipse ESCET downloads now contain a folder in the root of the archive, to properly support unpacking in e.g. a downloads directory (issue {escet-issue}87[#87]).
* This release is based on Eclipse 2021-06 (issues {escet-issue}28[#28] and {escet-issue}121[#121]).
* Improved Eclipse ESCET download filenames (issues {escet-issue}87[#87] and {escet-issue}92[#92]).
* Improved Eclipse ESCET version numbers in documentation, plugin/feature versions, and Eclipse ESCET IDE about dialog (issues {escet-issue}92[#92] and {escet-issue}103[#103]).
* Non-release builds now indicate they are a development build in the Eclipse About dialog (issue {escet-issue}26[#26]).
* Eclipse ESCET downloads for Linux previously included an 'executable' `about.html` file (issue {escet-issue}90[#90]).
* Crash reports now indicate where and how to report issues (issue {escet-issue}33[#33]).

=== Version 0.1 (2021-04-02)

The first release of the Eclipse ESCET project and toolkit.
This release is based on the initial contribution by the Eindhoven University of Technology (TU/e).

Most notable changes compared to the last TU/e release:

* A JDK is no longer bundled with the downloads.
A JDK must be installed separately and manually.
Future releases will again include a JDK.

This release is based on the Eclipse IDE version 2020-06 and supports Java 8.
