//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2022 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::_root_attributes.asciidoc[]

indexterm:[release, notes]

[[release-notes-chapter-index]]
== Eclipse ESCET release notes

The release notes for the versions of the Eclipse ESCET tools, as part of the Eclipse ESCET project, are listed below in reverse chronological order.

The release notes may refer to issues, the details for which can be found at the Eclipse ESCET link:https://gitlab.eclipse.org/eclipse/escet/escet/-/issues[GitLab issues page].

See also the release notes for the specific tools for more information:

* link:https://eclipse.org/escet/cif/release-notes.html[CIF release notes]
* link:https://eclipse.org/escet/chi/release-notes.html[Chi release notes]
* link:https://eclipse.org/escet/tooldef/release-notes.html[ToolDef release notes]

=== Version 0.6

TBD

New features:

* Added new Design Structure Matrix (DSM) clustering tool (issue #344).

Improvements and fixes:

* Small website style improvements (issue #367).

=== Version 0.5 (2022-03-29)

Improvements and fixes:

* Some small changes to the documentation and website (issues #271 and #335).
* The release notes for each version now contain the release date, with the exception of milestone releases and release candidates (issue #314).

=== Version 0.4 (2021-12-17)

Improvements and fixes:

* Introduced a brand new website (issue #35).
* Many website URLs have changed due to various website structure changes (issues #35 and #73).
* Various documentation/website textual improvements, style improvements and other changes (issues #35 and #54).
* The Eclipse ESCET end-user and development documentation have been split into two separate documentation sets (issue #73).
* SeText is now considered an internal developers tool.
It no longer has a website of its own.
Its documentation is now part of the Eclipse ESCET development documentation (issue #73).
* The Eclipse ESCET IDE executable is now named `eclipse-escet` or `eclipse-escet.exe`.
`eclipse.ini` is now named `eclipse-escet.ini` (issue #98).
* Eclipse ESCET now bundles Java 11.0.12 rather than Java 11.0.2 (issue #237).

=== Version 0.3 (2021-10-01)

Improvements and fixes:

* The website and Eclipse help now use multi-page HTML rather than a single HTML file, although the website still contains a link to the single-page HTML that allows easily searching the full documentation (issue #36).
* Enabled section anchors for documentation on the website, and disabled section anchors for Eclipse help (issue #36).
* Fixed macOS-specific instructions for tweaking Java performance settings via `eclipse.ini` (issue #179).
* Removed unsupported in-place update instructions from the documentation (issue #166).
* Several small documentation fixes and improvements (issue #166).

=== Version 0.2 (2021-07-07)

Improvements and fixes:

* Various documentation updates, including simpler installation instructions (issues #30 and #31).
* Java 11 is now included in the release and Java thus no longer needs to be installed separately (issues #29 and #30).
* The Eclipse ESCET IDE now includes the Eclipse Marketplace (issue #71).
* Linux command line scripts now work properly from any directory rather than only from the `bin` directory that contains them (issue #88).
* macOS releases are now packaged as `.dmg` files and with proper entitlements (issue #31).
* Eclipse ESCET downloads now contain a folder in the root of the archive, to properly support unpacking in e.g. a downloads directory (issue #87).
* This release is based on Eclipse 2021-06 (issues #28 and #121).
* Improved Eclipse ESCET download filenames (issues #87 and #92).
* Improved Eclipse ESCET version numbers in documentation, plugin/feature versions, and Eclipse ESCET IDE about dialog (issues #92 and #103).
* Non-release builds now indicate they are a development build in the Eclipse About dialog (issue #26).
* Eclipse ESCET downloads for Linux previously included an 'executable' `about.html` file (issue #90).
* Crash reports now indicate where and how to report issues (issue #33).

=== Version 0.1 (2021-04-02)

The first release of the Eclipse ESCET project and toolkit.
This release is based on the initial contribution by the Eindhoven University of Technology (TU/e).

Most notable changes compared to the last TU/e release:

* A JDK is no longer bundled with the downloads.
A JDK must be installed separately and manually.
Future releases will again include a JDK.

This release is based on the Eclipse IDE version 2020-06 and supports Java 8.
