//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2018, 2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::../_part_attributes.asciidoc[]

[[tools-cif2cif-chapter-convert-uncntrl-events-to-cntrl]]
== Convert uncontrollable events to controllable

indexterm:[CIF to CIF transformer,convert uncontrollable events to controllable]
indexterm:[convert uncontrollable events to controllable]
indexterm:[events,convert uncontrollable events to controllable]
This CIF to CIF transformation converts uncontrollable events to controllable.

As `tau` is neither controllable nor uncontrollable, it is not touched by this transformation.

indexterm:[convert uncontrollable events to controllable,supported specifications]

=== Supported specifications

This transformation supports a subset of CIF specifications.
The following restrictions apply:

* Component definitions and component instantiations are not supported.

indexterm:[convert uncontrollable events to controllable,preprocessing]

=== Preprocessing

No preprocessing is currently performed by this CIF to CIF transformation.
To increase the subset of specifications that can be transformed, apply the following <<tools-cif2cif-chapter-index,CIF to CIF transformations>> (in the given order):

* <<tools-cif2cif-chapter-elim-comp-def-inst>>

indexterm:[convert uncontrollable events to controllable,implementation]

=== Implementation details

Each uncontrollable event in the CIF specification is converted to controllable.
For instance, the following specification:

[source, cif]
----
uncontrollable a;
controllable b;

automaton aut:
  location l1:
    initial;
    marked;
    edge a goto l2;
  location l2:
    edge b goto l1;
end
----

is transformed to the following specification:

[source, cif]
----
controllable a;
controllable b;

automaton aut:
  location l1:
    initial;
    marked;
    edge a goto l2;
  location l2:
    edge b goto l1;
end
----

=== Renaming

Event names with the special prefix `u_` are renamed to preserve the event naming convention, see <<lang-tut-extensions-synthesis-evtctrl>>.
The prefix `u_` is replaced by `c_`.
In case the new global name is already in use in the specification, a suffix is also added.

=== Size considerations

Uncontrollable events are modified, the size of the specification neither grows nor shrinks.

=== Optimality

n/a

=== Annotations

This transformation does not process, add, or remove any annotations.
