//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2024 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::../_part_attributes.asciidoc[]

[[tools-cif2cif-chapter-remove-io-decls]]
== Remove I/O declarations

indexterm:[CIF to CIF transformer,remove I/O declarations]
indexterm:[remove I/O declarations]
indexterm:[I/O declaration,remove]
This CIF to CIF transformation removes I/O declarations from the specification.
This may reduce the size of the specification.
It may also lead to the specification being supported by more tools, as the I/O declarations may use features of the CIF language that certain tools don't support.

=== Supported specifications

This transformation supports all CIF specifications.

=== Preprocessing

n/a

indexterm:[remove I/O declarations,implementation]

=== Implementation details

All I/O declarations are removed from the specification.
I/O declarations include:

* <<tools-cifsim-output-print-chapter-ref-printdecl>>

* <<tools-cifsim-output-print-chapter-ref-printfile>>

* <<tools-cifsim-output-svgviz-chapter-cifsvg>>

This transformation removes all I/O declarations.
To only remove certain kinds of I/O declarations, see the following CIF to CIF transformations:

* <<tools-cif2cif-chapter-remove-print-decls>>

* <<tools-cif2cif-chapter-remove-cif-svg-decls>>

=== Renaming

n/a

indexterm:[remove I/O declarations,size considerations]

=== Size considerations

Since information is removed from the specification, the specification can only become smaller as a result of this transformation.

=== Optimality

n/a

=== Annotations

This transformation does not process, add, or remove any annotations.
