//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2020, 2022 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::../_part_attributes.asciidoc[]

.. index::
indexterm:[CIF to CIF transformer,remove unused algebraic variables]
indexterm:[remove unused algebraic variables]
indexterm:[unused algebraic variables,remove]

[[tools-cif2cif-chapter-remove-unused-alg-vars]]
== Remove unused algebraic variables

This CIF to CIF transformation removes unused algebraic variables from the specification.
As these removed algebraic variables are defined but not used, removing them does not alter the behavior modeled by the CIF specification.

== Supported specifications

This transformation supports a subset of CIF specifications.
The following restrictions apply:

* Component definitions and component instantiations are not supported.
* Automaton ``self`` references are not supported.

== Preprocessing

No preprocessing is currently performed by this CIF to CIF transformation.
To increase the subset of specifications that can be transformed, apply the following <<tools-cif2cif-chapter-index,CIF to CIF transformations>> (in the given order):

* <<tools-cif2cif-chapter-elim-comp-def-inst>>
* <<tools-cif2cif-chapter-elim-elim-self>>

== Implementation details

An algebraic variable is considered to be unused in a CIF specification if it is not used to compute a value in the model.
For instance, the following specification:

[source, cif]
----
  alg bool var1 = false;
  alg bool var2 = true;

  plant A:
    event a;
    location:
      edge a when var1;
  end
----

As algebraic variable `var2` is not used anywhere in the specification, it is transformed to the following specification:

[source, cif]
----
  alg bool var1 = false;

  plant A:
    event a;
    location:
      edge a when var1;
  end
----

Algebraic variables may also be used to define the value of another algebraic variable.
If the outer algebraic variable is not used, usage of algebraic variables to define its value do *not* count as 'used' for the latter algebraic variables.

For instance, the following specification:

[source, cif]
----
  alg bool var1 = false;
  alg bool var2 = not var1;
  alg bool var3 = var2;

  plant A:
    event a;
    location:
      edge a when var1;
  end
----

is transformed to the following specification:

[source, cif]
----
  alg bool var1 = false;

  plant A:
    event a;
    location:
      edge a when var1;
  end
----

While `var2` is used in defining the value of `var3`, `var2` is also considered to be unused, since `var3` is unused and `var2` is only used in defining the values of unused algebraic variables.
Algebraic variable `var1` is used in the value of `var2`, but also in a guard in plant `A`. The latter causes `var1` not to be removed.

== Renaming

n/a

== Size considerations

Since information is removed from the specification, the specification can only become smaller as a result of this transformation.

== Optimality

n/a
