//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2021, 2022 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::_part_attributes.asciidoc[]

[[rail-commandline]]
== Command-line arguments

The railroad diagram application has several command line arguments.
The following command line arguments can be specified, in the given order:

* The path to the input file that should be processed by the generator.
The file should contain a railroad diagram specification, like shown in <<rail-examples>>.

* The path to the output image file.

* The requested output format.
Specify `images` for a normal rail diagram `PNG` image.
Instead, `dbg-images` can be used to debug the diagram generator.

* Optionally, the path to the configuration file to use, as explained in the <<rail-customizing-output>> section.
If provided, the configuration file is used for customizing diagram layout.
If not provided, the default configuration is used.
