//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::_part_attributes.asciidoc[]

[[rail-chapter-index]]
== Rail diagram generator

The Eclipse ESCET rail diagram generator makes it easy to generate pretty and simple to understand syntax specifications.
The following topics explain the rail diagram generator in more detail:

* A short *introduction* about the use of rail diagrams can be found in <<rail-introduction>>.
* *Hands-on examples* are in the <<rail-examples>> section.
* How to *Fine-tune the output* is described in <<rail-customizing-output>>.
* *Using the application from the command line* is explained in the <<rail-commandline>> section.
* The *formal definition* of the *rail diagram input language* is shown in <<rail-lexical-syntax>> and <<rail-grammar>>.
* And finally, helpful tips on *debugging* problems in the generator can be found in <<rail-debugging>>.
