/////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2021 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the terms
// of the MIT License which is available at https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
/////////////////////////////////////////////////////////////////////////////////

include::_root_attributes.asciidoc[]

indexterm:[contact]

[[contact-chapter-index]]
== Contact information

Thanks for your interest in Eclipse Supervisory Control Engineering Toolkit
(Eclipse ESCET) project.

You can interact with the Eclipse ESCET community and its developers in
various ways:

link:https://www.eclipse.org/forums/index.php/f/527/[Eclipse ESCET forum]::
If you have any questions regarding the Eclipse ESCET project, any of its
tools, or how to use them, feel free to ask them on the project forum.

<<developer-issue-tracking-chapter-index,Issue tracking>>::
If you wish to browse existing issues or report new ones, then see the
issue tracking section for more information.

<<developer-chapter-index,Developer information>>::
If you specifically want to contact the Eclipse ESCET developers concerning
development related activities, want to contribute to the Eclipse ESCET
project, or want to browse the source code, then see the developer
information.
