= Notices for Eclipse ESCET(TM)

This content is produced and maintained by the Eclipse Supervisory Control Engineering Toolkit (Eclipse ESCET(TM)) project.

For more information, see the Eclipse ESCET main repository:

* https://gitlab.eclipse.org/eclipse/escet/escet

== Trademarks

Eclipse ESCET and ESCET are trademarks of the Eclipse Foundation. Eclipse, and the Eclipse Logo are registered trademarks of the Eclipse Foundation.
Other names may be trademarks of their respective owners.

== Copyright

All content is the property of the respective authors or their employers.
For more information regarding authorship of content, please consult the listed source code repository logs.

== Declared Project Licenses

This program and the accompanying materials are made available under the terms of the MIT License which is available at https://opensource.org/licenses/MIT

SPDX-License-Identifier: MIT

== Source Code

The project maintains the following source code repositories:

* https://gitlab.eclipse.org/eclipse/escet/escet.git
* https://gitlab.eclipse.org/eclipse/escet/escet-website.git

These can also be accessed via a web interface:

* https://gitlab.eclipse.org/eclipse/escet/escet
* https://gitlab.eclipse.org/eclipse/escet/escet-website

See `CONTRIBUTING.asciidoc` for more information.

== Third-party Content

See the various `*legal*` files in this repository.

== Cryptography

Content may contain encryption software.
The country in which you are currently may have restrictions on the import, possession, and use, and/or re-export to another country, of encryption software.
BEFORE using any encryption software, please check the country's laws, regulations and policies concerning the import, possession, or use, and re-export of encryption software, to see if this is permitted.
