<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TcPlcObject ProductVersion="3.1.0.18" Version="1.1.0.1">
  <POU Name="func_f2">
    <Declaration><![CDATA[FUNCTION func_f2: BOOL
VAR_INPUT
    farg_f2_p: BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[func_f2 := ifExprFunc2(farg_f2_p);
RETURN;]]></ST>
    </Implementation>
    <ObjectProperties/>
  </POU>
</TcPlcObject>
