/////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2021 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the terms
// of the MIT License which is available at https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
/////////////////////////////////////////////////////////////////////////////////

include::../_part_attributes.asciidoc[]

[[tools-cifsim-chapter-distr-seeds]]
== Stochastic distributions and seeds

indexterm:[CIF simulator,stochastic distributions]
indexterm:[seed,stochastic distributions]
<<lang-tut-stochastics-chapter-intro,Stochastics>> can be used to model randomness in CIF models.
The CIF simulator exhibits <<lang-tut-stochastics-chapter-pseudo-randomness,pseudo-randomness>>.
This page explains how to influence that pseudo-randomness.

The randomness of the stochastic distributions is implemented in the CIF simulator using link:http://en.wikipedia.org/wiki/Pseudorandom_number_generator[pseudorandom number generators] (PRNGs).
The PRNG used is the link:http://en.wikipedia.org/wiki/Mersenne_twister[Mersenne Twister].
The sequences of random numbers that are generated by the MT are not truly random.
They are pseudorandom, as they start to repeat after some time.
The Mersenne Twister however, has a very long _period_ of 2^19937^ - 1 numbers.

Since the sequence of generated random numbers is always the same, the only way to vary it, is to use a different starting place.
The starting place is determined by the initial link:http://en.wikipedia.org/wiki/Random_seed[seed], which can be configured through the menu:Initial seed for stochastic distributions[] option (menu:Simulator[] category).
If specified, it must be a value in the range [1 .. 2^30^].
If it is not specified, a random initial seed in that range is chosen by the simulator.
If a random initial seed is chosen, and it is used, it is <<tools-cifsim-output-normal-seeds,printed>> to the console.

The initial seed as provided by the option, is used for the first stochastic distribution that is created.
Each subsequent distribution uses the next available seed.
That is, if you specify an initial seed of 5, then the first distribution is created with an initial seed of 5, the next one uses 6, the third one uses 7, etc.
The initial seeds are kept in the range [1 .. 2^30^].
After seed 2^30^, 1 is used as seed, then 2 is used as seed, etc.

Simulating the same specification multiple times, using the same initial seed, results in the same samples.
Therefore, using a fixed seed can make your simulation deterministic, even though you use stochastic distributions to introduce randomness into your specification.
