//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2021 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::../_part_attributes.asciidoc[]

[[tools-cifsim-chapter-max-time-point-tol]]
== Maximum time point tolerance

indexterm:[CIF simulator,maximum time point tolerance]

WARNING: This page is primarily intended for the developers of the CIF simulator, and not its end users.

The CIF simulator internally often queries the trajectories computed by the <<tools-cifsim-solver-chapter-index,ODE solver>>.
Due to the limited precision of binary floating point number representations, requests of time points for which no exact match is present in the trajectories, but for which a very close match is present, are allowed.
The simulator compensates for these small deviations, to avoid accumulation of such deviations.

indexterm:[ulp]
The simulator uses the value of the _Maximum time point tolerance_ option (_Simulation_ category) to determine whether two time points are close enough to each other to constitute a match.
The tolerance is given in link:https://en.wikipedia.org/wiki/Unit_in_the_last_place[ulps] (_units in the last place_, or _units of least precision_).
One ulp is the difference between two subsequent floating point numbers, for the limited precision binary floating point number representation used by the simulator.
That is, two floating point numbers are one ulp away from each other, if there is no other floating point number between them, that can be represented using the floating point number representation used by the simulator.
Since an ulp increases as the floating point numbers increase, the tolerance is thus relative to the values of the time points.

The tolerance values chosen using the option must be in the range [1 .. 2^30^].
The default tolerance is 2^10^ (= 1024) ulps.
The default tolerance should suffice, but if it doesn't, you may be presented with an error like this:

[source, console]
----
ERROR: Simulation resulted in a runtime error, for state: time=0.0, x=1.0.
CAUSE: Requested time point "1.6000000000000005" is "2.0" ulps (1 ulp = 2.220446049250313e-16) away from the closest time point in the trajectories "1.6", which is farther away than the maximum tolerance of "1" ulps. You can try increasing the value of the maximum time point tolerance option. Please also contact the development team.
----

If you get such an error, you can try to increase the tolerance using the _Maximum time point tolerance_ option, in order to be able to continue your simulation.
However, as this shouldn't actually happen, you should also contact the development team, who will then figure out why the default tolerance doesn't suffice for your model.
