//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::_part_attributes.asciidoc[]

[[tools-chapter-cif-explorer]]
== CIF explorer

indexterm:[CIF explorer]
indexterm:[tools,CIF explorer]
indexterm:[single,state space,explorer]
indexterm:[single,state space,generator]
indexterm:[see: explorer,CIF explorer]
The CIF explorer unfolds the state space expressed by a CIF specification, in an untimed setting.

It takes a CIF model and iteratively explores the states using event transitions, unfolding the state space.
Time transitions are never taken.
The explorer will return a deadlock state when forced into a time step.
Continuous variables are allowed, but behave much like discrete variables due to lack of time steps.

Available output forms include a CIF automaton of the state space, and a report with details of the found states.

The statespace is computed in terms of the states of the CIF specification, based on the current locations of its automata and the values of its variables.
The resulting statespace is an NFA or a DFA, but is not necessarily https://en.wikipedia.org/wiki/DFA_minimization[minimal], even with the <<tools-cif-explorer-enable-edge-minimization,edge minimization>> option enabled.
You can minimize it using the <<tools-eventbased-chapter-dfa-minimization,DFA minimizer>>, assuming the state space satisfies that tool's preconditions.

indexterm:[CIF explorer,start]

=== Starting the program

The explorer can be started in the following ways:

* In Eclipse, right click a `.cif` file in the _Project Explorer_ tab or _Package Explorer_ tab and choose menu:CIF miscellaneous tools[Explore untimed state space...].

* In Eclipse, right click an open text editor for a `.cif` file and choose menu:CIF miscellaneous tools[Explore untimed state space...].

* Use the `cifexplorer` tool in a ToolDef script.
See the <<tools-scripting-chapter-intro,scripting documentation>> and <<tools-scripting-chapter-tools,tools overview>> page for details.

* Use the `cifexplorer` command line tool.

indexterm:[CIF explorer,options]

[[tools-chapter-cif-explorer-options]]
=== Options

Besides the general application options, the application has the following options:

* _Input file path_: The absolute or relative file system path to the input CIF specification.

[[tools-cif-explorer-enable-edge-minimization]]
* _Enable edge minimization_: Enable edge minimization to remove duplicate edges of the state space, before printing statistics, and writing output files.
Two edges are duplicates if they have the same source and target states, and the same event.
The communication value, if any, is ignored.
Enabled by default.

* _Enable statistics_: Enable printing of statistics of the resulting state space to the console.
Statistics include the number of states and the number of edges of the resulting state space.
It is recommended to enable the edge minimization option when printing statistics.
Enabled by default.

[[tools-cif-explorer-enable-cif-output]]
* _Enable CIF output_: Enable output of states and edges as a CIF automaton.
Enabled by default.
See for more information the section on <<tools-chapter-cif-explorer-output-cif,output as a CIF automaton>>.

[[tools-cif-explorer-add-state-annos]]
* _Add state annotations_: Add state annotations to the locations of the CIF automaton in the output CIF specification.
Enabled by default.
See for more information the section on <<tools-chapter-cif-explorer-output-cif,output as a CIF automaton>>.

* _Output file path_: The absolute or relative file system path of the output CIF specification with the generated state space as a CIF automaton.

[[tools-cif-explorer-name]]
* _Name_: The name of the resulting statespace automaton.
If not specified, it defaults to `statespace`.
If the resulting statespace automaton has a name that conflicts with an existing declaration, it is automatically renamed to have a non-conflicting name.
See for more information the section on <<tools-chapter-cif-explorer-output-cif,output as a CIF automaton>>.

* _Enable report_: Enable writing a detailed report on the found states.
Disabled by default.

* _Report file path_: The absolute or relative file system path of the report file.
If specified, option _Enable report_ is implied.

* _Print progress_: The number of states to process before printing progress information.
Must be a non-negative integer number.
May be `off` to disable progress information.
The default is to print progress information after processing 1000 states.

The CIF output file is written if the _Enable CIF output_ option is set, or if a path is supplied with the _Output file path_ option.
If the latter is given, its value is used as the path for writing the CIF file.
If only the _Enable CIF output_ option is set, the value of the _Input file path_ option is used, where the `.cif` extension is removed (if present), and a `+_statespace.cif+` suffix is added.

The report file is written if the _Enable report_ option is set, or if a path is supplied with the _Report file path_ option.
If the latter is given, its value is used as the path for writing the report file.
If only the _Enable report_ option is set, the value of the _Input file path_ option is used, where the `.cif` extension is removed (if present), and a `+_report.txt+` suffix is added.

If both the CIF output and the report file output are disabled, the resulting state space is not outputted at all.
In such cases, the state space explorer acts as a verifier for runtime errors, which can make the exploration fail.
If exploration completes without errors, the explorer has verified that no runtime errors occur.
Runtime errors include failures to compute values, such as division by zero, as well as assignments that assign values to variables that are outside the allowed bounds/ranges of the variables.

indexterm:[CIF explorer,supported specifications]

=== Supported specifications

The explorer supports a subset of CIF specifications.
The following restrictions apply:

* Usage of distribution types and distribution standard library functions is not supported.

* Usage of derivatives is not supported.

* External user-defined functions are not supported.

* Input variables are not supported.

* Specifications with more than 2^31^ - 1 = 2,147,483,647 potential initial states are not supported.

The following information from the specification is ignored:

* Automaton and invariant supervisory kinds.
A warning is printed if a requirement automaton or requirement invariant is encountered.

* Controllability of events.

* I/O declarations are ignored.
A warning is printed if a CIF/SVG input declaration is encountered.

* Annotations are ignored.
If outputting a CIF model is <<tools-cif-explorer-enable-cif-output,enabled>>, the produced model may have annotations.
See for more information the section on <<tools-chapter-cif-explorer-output-cif,output as a CIF automaton>>.

indexterm:[CIF explorer,preprocessing]

=== Preprocessing

Prior to exploration, the following <<tools-cif2cif-chapter-index,CIF to CIF transformations>> are applied as preprocessing (in the given order), to increase the subset of CIF specifications that can be explored:

* <<tools-cif2cif-chapter-remove-io-decls>>

* <<tools-cif2cif-chapter-elim-comp-def-inst>>

* <<tools-cif2cif-chapter-elim-self>>

In addition it applies the <<tools-cif2cif-chapter-simplify-values-no-refs-optimized>> CIF to CIF transformation to speed up processing.

[[tools-chapter-cif-explorer-output-cif]]
=== Output as a CIF automaton

If outputting a CIF model is <<tools-cif-explorer-enable-cif-output,enabled>>, a CIF specification is created and written to a file.
The state space is represented by an automaton, each state is represented by a location of that automaton, and the edges between states are represented as edges between locations.
The automaton is named as configured using the <<tools-cif-explorer-name,_Name_ option>>.
If the state space is empty, the automaton has a single non-initial location.

If adding <<lang-tut-extensions-chapter-annotations-state,state annotations>> is <<tools-cif-explorer-add-state-annos,enabled>> each location is annotated with a state annotation that indicates the current location of each automaton and the current value of each variable.
If the state space is empty, the single location in the automaton does not have a state annotation, regardless of whether the option to add state annotations is enabled or not.
For most values, the value is simply represented by a literal.
For instance, boolean values are represented by boolean literals `true` and `false`, and a list of integers is represented by a list literal, such as `[1, 2, 3]`.
There are some exceptions:

[cols="1,4"]
|===
| Location / value | Represented as

| Location of an automaton
| String with the name of the location, or `"*"` for a nameless location.
If the name is a keyword, it is not escaped.

| Enumeration literal
| String with the non-escaped name of the literal.
If the name is a keyword, it is not escaped.

| Function
| String with the non-escaped absolute name of the function.
For functions that represent a default initial value of a variable with a function type, `"*"` is used as function name.
Keywords in the absolute names are not escaped.
|===
