//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::../_part_attributes.asciidoc[]

[[lang-ref-extensions-annotations-state]]
== State annotations

WARNING: Annotations are currently an experimental work-in-progress language feature.
Their design may change in a backward incompatible manner.

State <<lang-ref-extensions-annotations,annotations>> can be used to add state information to CIF elements.
For basic information on state annotations, see the <<lang-tut-extensions-chapter-annotations-state,language tutorial>>.
Here we discuss further details.

State annotations (`@state`) can be added to the following elements in CIF specifications:

* Locations of automata.

The <<lang-ref-extensions-annotations-constraints,general constraints>> that apply to all annotations, also apply to state annotations.
