//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2010, 2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available
// under the terms of the MIT License which is available at
// https://opensource.org/licenses/MIT
//
// SPDX-License-Identifier: MIT
//////////////////////////////////////////////////////////////////////////////

include::_root_attributes.asciidoc[]

indexterm:[release, notes]

[[release-notes-chapter-index]]
== ToolDef release notes

The release notes for the versions of ToolDef and the associated tools, as part of the Eclipse ESCET project, are listed below in reverse chronological order.

See also the Eclipse ESCET link:https://eclipse.dev/escet/{escet-website-version}/release-notes.html[toolkit release notes] covering those aspects that are common to the various Eclipse ESCET tools.

=== Version 0.10

TBD

=== Version 0.9 (2023-03-31)

Improvements and fixes:

* The ToolDef documentation has some improvements related to 'file separator' terminology (issue {escet-issue}450[#450]).
* The ToolDef documentation for the `chfileext` tool has some formatting fixes (issue {escet-issue}536[#536]).

=== Version 0.8 (2022-12-21)

Improvements and fixes:

* The `filenewer` tool now only checks for modification time differences that are at least one millisecond (issue {escet-issue}259[#259]).
* Small documentation improvement for the `filenewer` tool documentation (issue {escet-issue}456[#456]).
* Normally, `.tooldef` files are opened with the ToolDef text editor.
Large files are now however opened with the default non-ToolDef text editor to avoid performance issues.
You can open a file in an editor of your choosing by right clicking it and selecting menu:Open With[] and then selecting the editor of your choosing, or choosing menu:Other...[] to open a dialog to choose from a larger selection of editors (issue {escet-issue}199[#199]).

=== Version 0.7 (2022-09-30)

New features:

* The ToolDef text editor now has theming support, and comes with a dark theme in addition to the existing light theme.
The text editor now automatically uses its dark theme when the Eclipse built-in dark theme is used, and uses a light theme otherwise.
The text editor theming behavior can be configured via the Eclipse Preferences dialog (issue {escet-issue}347[#347]).

Improvements and fixes:

* The ToolDef text editor light theme's default color has changed from a near-black slightly-brown color to pure black (issue {escet-issue}347[#347]).

=== Version 0.6 (2022-07-07)

Improvements and fixes:

* Links in the documentation to non-ToolDef ESCET documentation webpages now use version-specific URLs (issue {escet-issue}386[#386]).
* The issue numbers in the release notes now link to the corresponding GitLab issue (issue {escet-issue}396[#396]).
* Small website style improvements (issue {escet-issue}367[#367]).

=== Version 0.5 (2022-03-29)

Improvements and fixes:

* The release notes for each version now contain the release date, with the exception of milestone releases and release candidates (issue {escet-issue}314[#314]).

=== Version 0.4 (2021-12-17)

Improvements and fixes:

* Introduced a brand new website (issue {escet-issue}35[#35]).
* Many website URLs have changed due to various website structure changes (issues {escet-issue}35[#35] and {escet-issue}73[#73]).
* Various documentation/website textual improvements, style improvements and other changes (issues {escet-issue}35[#35] and {escet-issue}54[54]).
* Multiple small error message improvements (issue {escet-issue}248[#248]).

=== Version 0.3 (2021-10-01)

Improvements and fixes:

* The website and Eclipse help now use multi-page HTML rather than a single HTML file, although the website still contains a link to the single-page HTML that allows easily searching the full documentation (issue {escet-issue}36[#36]).
* Enabled section anchors for documentation on the website, and disabled section anchors for Eclipse help (issue {escet-issue}36[#36]).
* Several small documentation fixes and improvements (issue {escet-issue}166[#166]).

=== Version 0.2 (2021-07-07)

This release contains no specific changes for ToolDef.

=== Version 0.1 (2021-04-02)

The first release of ToolDef as part of the Eclipse ESCET project.
This release is based on the initial contribution by the Eindhoven University of Technology (TU/e).

Most notable changes compared to the last TU/e release:

* We no longer use separate language and tool versions.
The `.tooldef2` file extension has been changed to `.tooldef` as part of this change.
