<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TcPlcObject ProductVersion="3.1.0.18" Version="1.1.0.1">
  <POU Name="func_pf">
    <Declaration><![CDATA[FUNCTION func_pf: DINT
VAR_INPUT
    farg_pf_x: DINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[func_pf := projArray0(makeArray0(1, 2, 3, 4, 5), farg_pf_x);
RETURN;]]></ST>
    </Implementation>
    <ObjectProperties/>
  </POU>
</TcPlcObject>
