<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TcPlcObject ProductVersion="3.1.0.18" Version="1.1.0.1">
  <POU Name="projArray1">
    <Declaration><![CDATA[FUNCTION projArray1: ARRAY[0..4] of DINT
VAR_INPUT
    arr: ARRAY[0..1] of ARRAY[0..4] of DINT;
    idx: DINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[projArray1 := arr[normProjIdx(idx, 2)];]]></ST>
    </Implementation>
    <ObjectProperties/>
  </POU>
</TcPlcObject>
