<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TcPlcObject ProductVersion="3.1.0.18" Version="1.1.0.1">
  <POU Name="proj16_TupleStruct_3">
    <Declaration>
      <![CDATA[FUNCTION proj16_TupleStruct_3: BOOL
VAR_INPUT
    tuple: TupleStruct_3;
END_VAR]]>
    </Declaration>
    <Implementation>
      <ST>
        <![CDATA[proj16_TupleStruct_3 := tuple.field16;]]>
      </ST>
    </Implementation>
    <ObjectProperties/>
  </POU>
</TcPlcObject>
