<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TcPlcObject ProductVersion="3.1.0.18" Version="1.1.0.1">
  <POU Name="proj39_TupleStruct_5">
    <Declaration>
      <![CDATA[FUNCTION proj39_TupleStruct_5: LREAL
VAR_INPUT
    tuple: TupleStruct_5;
END_VAR]]>
    </Declaration>
    <Implementation>
      <ST>
        <![CDATA[proj39_TupleStruct_5 := tuple.field39;]]>
      </ST>
    </Implementation>
    <ObjectProperties/>
  </POU>
</TcPlcObject>
